GXProductSettings:
  title: GXProductSettings
  type: object
  required:
    - detailsTemplate
    - optionsDetailsTemplate
    - optionsListingTemplate
    - showOnStartpage
    - showQuantityInfo
    - showWeight
    - showPriceOffer
    - showAddedDateTime
    - priceStatus
    - minOrder
    - graduatedQuantity
    - onSitemap
    - sitemapPriority
    - sitemapChangeFrequency
    - propertiesDropdownMode
    - startpageSortOrder
    - showPropertiesPrice
    - propertiesCombisQuantityCheckMode
    - usePropertiesCombisShippingTime
    - usePropertiesCombisWeight
    - groupPermissions
  properties:
    detailsTemplate:
      type: string
    optionsDetailsTemplate:
      type: string
    optionsListingTemplate:
      type: string
    showOnStartpage:
      type: boolean
    showQuantityInfo:
      type: boolean
    showWeight:
      type: boolean
    showPriceOffer:
      type: boolean
    showAddedDateTime:
      type: boolean
    priceStatus:
      type: integer
      format: int64
      description: 'Provide: "0" for normal, "1" for price on request and "2" for not available for purchase.'
    minOrder:
      type: integer
      format: int64
    graduatedQuantity:
      type: integer
      format: int64
    onSitemap:
      type: boolean
    sitemapPriority:
      type: string
    sitemapChangeFrequency:
      type: string
    propertiesDropdownMode:
      type: string
    startpageSortOrder:
      type: integer
      format: int64
    showPropertiesPrice:
      type: boolean
    propertiesCombisQuantityCheckMode:
      type: integer
      format: int64
    usePropertiesCombisShippingTime:
      type: boolean
    usePropertiesCombisWeight:
      type: boolean
    groupPermissions:
      type: array
      items:
        $ref: '#/definitions/GXProductSettingsGroupPermission'
  example:
    settings:
      detailsTemplate: "standard.html"
      optionsDetailsTemplate: "product_options_dropdown.html"
      optionsListingTemplate: "product_options_dropdown.html"
      showOnStartpage: false
      showQuantityInfo: true
      showWeight: false
      showPriceOffer: true
      showAddedDateTime: false
      priceStatus: 0
      minOrder: 1
      graduatedQuantity: 1
      onSitemap: true
      sitemapPriority: '0.5'
      sitemapChangeFrequency: "daily"
      propertiesDropdownMode: "dropdown_mode_1"
      startpageSortOrder: 0
      showPropertiesPrice: true
      usePropertiesCombisQuantity: false
      usePropertiesCombisShippingTime: true
      usePropertiesCombisWeight: false
