ProductsDeleteSuccessResponse:
    title: ProductsDeleteSuccessResponse
    required:
        - code
        - status
        - action
        - resource
        - productId
    properties:
        code:
            type: integer
            format: int64
        status:
            type: string
        action:
            type: string
        resource:
            type: string
        productId:
            type: integer
            format: int64