@startuml
'https://plantuml.com/class-diagram

!theme gambio from ../gambio-puml-theme

package Gambio\Admin\Modules\Customer\Submodules\Memos\Services {
	class CustomerMemoFactory {
		+ createCustomerMemoIds(CustomerMemoId ...$customerMemoIds): CustomerMemoIds
		+ createCustomerMemos(CustomerMemo ...$customerMemos): CustomerMemos
		+ createCustomerId(int $customerId): CustomerId
		+ createCreatorId(int $creatorId): CreatorId
		+ createCustomerMemoId(int $customerMemoId): CustomerMemoId
	}

	interface CustomerMemoReadService {
		+ getCustomerMemos(int $customerId): CustomerMemos
		+ getCustomerMemoById(int $customerMemoId): CustomerMemo
	}

	interface CustomerMemoFilterService {
		+ filterCustomerMemos(int $customerId, ...): CustomerMemos
		+ getCustomerMemosTotalCount(int $customerId, ...): int
	}

	interface CustomerMemoRepository {
	    + filterCustomerMemos(CustomerId $customerId, ...): CustomerMemos
        + getCustomerMemosTotalCount(CustomerId $customerId, ...): int
        + getCustomerMemos(CustomerId $customerId): CustomerMemos
        + getCustomerMemoById(CustomerMemoId $customerMemoId): CustomerMemo
        + createCustomerMemo(CustomerId $customerId, CreatorId $creatorId, string $content): CustomerMemoId
        + createMultipleCustomerMemos(array ...$creationArguments): CustomerMemoIds
        + storeCustomerMemos(CustomerMemo ...$customerMemos): void
        + deleteCustomerMemosByMemoIds(CustomerMemoId ...$customerMemosIds): void
        + deleteCustomerMemosByCustomerIds(CustomerId ...$customerIds): void
	}

	interface CustomerMemoWriteService {
		+ createCustomerMemo(int $customerId, int $creatorId, string $content): CustomerMemoId
		+ createMultipleCustomerMemos(array ...$creationArguments): CustomerMemoIds
		+ storeCustomerMemos(CustomerMemo ...$customerMemos): void
		+ deleteCustomerMemosByMemoIds(int ...$customerMemosIds): void
		+ deleteCustomerMemosByCustomerIds(int ...$customerIds): void
	}
}

package Gambio\Admin\Modules\Customer\Submodules\Memos\Services\Exceptions {
	left to right direction

	class CustomerMemoDoesNotExistException
	class CreationOfCustomerMemoFailedException
	class DeletionOfCustomerMemoFailedException
	class StorageOfCustomerMemoFailedException
}



CustomerMemoDoesNotExistException -up-|> Exception
CreationOfCustomerMemoFailedException -up-|> Exception
DeletionOfCustomerMemoFailedException -up-|> Exception
StorageOfCustomerMemoFailedException -up-|> Exception

@enduml