GXCustomerGroupConfigurations:
    title: GXCustomerGroupConfigurations
    type: object
    required:
        - minOrder
        - maxOrder
        - discount
        - otDiscount
        - unallowedPaymentModules
        - unallowedShippingModules
    properties:
        minOrder:
            type: integer
            format: int64
        maxOrder:
            type: integer
            format: int64
        discount:
            type: integer
            format: int64
        otDiscount:
            type: integer
            format: int64
        unallowedPaymentModules:
            type: array
            items:
                type: string
        unallowedShippingModules:
            type: array
            items:
                type: string
    example:
        minOrder: 2.5
        maxOrder: 20
        discount: 0.5
        otDiscount: 0
        unallowedPaymentModules:
        - "paypal"
        - "cod"
        - "moneyorder"
        unallowedShippingModules:
        - "selfpickup"
