site_name: Developer Documentation
site_url: https://developers.gambio.de/
docs_dir: ./docs
site_dir: ./site
copyright: Copyright &copy; 2024 Gambio GmbH
theme:
  name: material
  custom_dir: html
  favicon: favicon.ico
  logo: logo.svg
  language: en
  palette:
    scheme: gambio
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - toc.autohide
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - navigation.top
extra:
  generator: false
  social:
    - icon: gambio/white
      link: https://www.gambio-support.de
      name: Gambio Kundenportal
    - icon: fontawesome/brands/x
      link: https://x.com/gambio
    - icon: fontawesome/brands/github
      link: https://github.com/gambio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gambio-gmbh
extra_css:
  - assets/css/extra.css
nav:
  - Development Environment:
      - develop-environment/index.md
      - develop-environment/development-tools.md
      - develop-environment/setup-project.md
      - Supported PHP Versions: https://tracker.gambio-server.net/projects/gxdoc/wiki/Unterst%C3%BCtzte_PHP-Versionen
  - Architecture and Framework:
      - framework/index.md
      - framework/application-core.md
      - More information about ...:
          - framework/details/application-layers.md
          - framework/details/autoloading.md
          - framework/details/di-container.md
          - framework/details/service-provider.md
      - Technical components:
          - framework/technical-components/index.md
          - framework/technical-components/authentication.md
          - framework/technical-components/cache.md
          - framework/technical-components/configurations.md
          - framework/technical-components/database.md
          - framework/technical-components/emails.md
          - framework/technical-components/environment.md
          - framework/technical-components/events.md
          - framework/technical-components/languages.md
          - framework/technical-components/logging.md
          - framework/technical-components/permissions.md
          - framework/technical-components/pricing.md
          - framework/technical-components/routing.md
          - framework/technical-components/text-phrases.md
          - framework/technical-components/verification.md
      - Business components:
          - framework/business-components/index.md
          - framework/business-components/admin-access.md
          - framework/business-components/customer.md
          - framework/business-components/customer-addon-value.md
          - framework/business-components/customer-memo.md
          - framework/business-components/customer-legacy-services.md
          - framework/business-components/image-list.md
          - framework/business-components/option.md
          - framework/business-components/parcel-service.md
          - framework/business-components/product-option.md
          - framework/business-components/product-variant.md
          - framework/business-components/statistics-overview.md
          - framework/business-components/tracking-code.md
          - framework/business-components/user-configuration.md
          - framework/business-components/withdrawal.md
      - framework/legacy-architecture.md
  - Module Development:
      - module-development/index.md
      - General Development:
          - module-development/general/gx-modules.md
          - module-development/general/defining-a-module.md
          - module-development/general/extending-html.md
          - module-development/general/languages-text-phrases.md
          - module-development/general/all-extenders.md
      - Store Development:
          - module-development/store/adding-css.md
          - module-development/store/adding-js.md
          - module-development/store/creating-http-controller.md
          - module-development/store/creating-theme.md
      - Admin Development:
          - module-development/admin/define-http-routes.md
          - module-development/admin/http-actions.md
          - module-development/admin/admin-menu-json.md
          - module-development/admin/gx-modules-json.md
          - module-development/admin/custom-module-center-module.md
          - module-development/admin/custom-configuration-page.md
      - module-development/guidelines.md
      - module-development/sample-modules.md
  - Theme Development:
      - theme-development/index.md
      - theme-development/architecture.md
      - theme-development/extension.md
      - theme-development/content-manager.md
      - theme-development/html-templates.md
      - theme-development/styles.md
      - theme-development/scripts.md
      - theme-development/text-phrases.md
      - theme-development/final.md
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - html/.icons
  - def_list
  - footnotes
  - abbr
  - extra
  - admonition
  - meta
  - attr_list
  - toc:
      toc_depth: 6
      permalink: true
plugins:
  - section-index
  - mkdocs-nav-enhancements
  - tags
  - search:
      lang: de
      separator: '[\s\-\.]+'
