productArrayDeleteResponse:
    title: productArrayDeleteResponse
    type: object
    required:
        - deleted
        - errors
    properties:
        deleted:
            type: array
            items:
                type: 'integer'
                format: 'int64'
        errors:
            type: array
            items:
                $ref: '#/definitions/defaultErrorResponse'