productArrayPutResponse:
    title: productArrayPutResponse
    type: object
    required:
        - updated
        - errors
    properties:
        updated:
            type: array
            items:
                $ref: '#/definitions/GXProduct'
        errors:
            type: array
            items:
                $ref: '#/definitions/defaultErrorResponse'