@startuml
'https://plantuml.com/class-diagram

!theme gambio from ../gambio-puml-theme

interface IteratorAggregate

package Gambio\Core\Event\EventRaisingEntity {
	abstract class AbstractEventRaisingEntity
}

package Gambio\Admin\Modules\Customer\Submodules\History\Model\Collections {
    class CustomerHistory {
        + {static} create(CustomerHistoryEntry ...$customerMemos): CustomerHistory
        + toArray(string $datetimeFormat = 'Y-m-d H:i:s'): array
    }
}


package Gambio\Admin\Modules\Customer\Submodules\History\Model {
    class CustomerHistoryEntry <<Aggregate Root>> {
        - payload: array
        - type: string
        - date: DateTimeImmutable
        --
        + {static} create(\
        \n    CustomerId $customerId, array $payload,\
        \n    string $type, DateTimeImmutable $date\
        \n): CustomerHistoryEntry
        ..
        + toArray(string $datetimeFormat = 'Y-m-d H:i:s'): array
        + customerId(): int
        + content(): array
        + type(): string
        + date(string $datetimeFormat = 'Y-m-d H:i:s'): string
    }
    note bottom of CustomerHistoryEntry: payload must be a map
}

package Gambio\Admin\Modules\Customer\Submodules\History\Model\ValueObjects {

	class CustomerId {
		- value: int
		--
		+ {static} create(int $customerId): CustomerId
		..
		+ value(): int
	}

}

AbstractEventRaisingEntity <|-- CustomerHistoryEntry

CustomerHistoryEntry *-- CustomerId

CustomerHistory o- CustomerHistoryEntry
CustomerHistory --|> IteratorAggregate


@enduml