categorySettings:
    title: categorySettings
    type: object
    required:
        - categoryListingTemplate
        - productListingTemplate
        - sortColumn
        - sortDirection
        - onSitemap
        - sitemapPriority
        - sitemapChangeFrequency
        - showAttributes
        - showGraduatedPrice
        - showQuantity
        - showQuantityInfo
        - showSubCategories
        - showSubCategoryImages
        - showSubCategoryNames
        - showSubCategoryProducts
        - isViewModeTiled
        - showCategoryFilter
        - filterSelectionMode
        - filterValueDeactivation
        - groupPermissions
    properties:
        categoryListingTemplate:
            type: string
        productListingTemplate:
            type: string
        sortColumn:
            type: string
        sortDirection:
            type: string
            enum:
                - ASC
                - DSC
        onSitemap:
            type: boolean
        sitemapPriority:
            type: string
        sitemapChangeFrequency:
            type: string
        showAttributes:
            type: boolean
        showGraduatedPrice:
            type: boolean
        showQuantity:
            type: boolean
        showQuantityInfo:
            type: boolean
        showSubCategories:
            type: boolean
        showSubCategoryImages:
            type: boolean
        showSubCategoryNames:
            type: boolean
        showSubCategoryProducts:
            type: boolean
        showCategoriesImageInDescription:
            type: boolean
        isViewModeTiled:
            type: boolean
        showCategoryFilter:
            type: boolean
        filterSelectionMode:
            type: integer
            format: int64
        filterValueDeactivation:
            type: integer
            format: int64
        groupPermissions:
            type: array
            items:
                $ref: '#/definitions/categoryGroupPermissions'
    example:
        categoryListingTemplate: "category_listing.html"
        productListingTemplate: "product_listing_v1.html"
        sortColumn: "p.products_price"
        sortDirection: "ASC"
        onSitemap: true
        sitemapPriority: '0.5'
        sitemapChangeFrequency: "daily"
        showAttributes: false
        showGraduatedPrice: false
        showQuantity: true
        showQuantityInfo: false
        showSubCategories: true
        showSubCategoryImages: true
        showSubCategoryNames: true
        showSubCategoryProducts: false
        isViewModeTiled: false
        showCategoryFilter: false
        filterSelectionMode: 0
        filterValueDeactivation: 0