@startuml
'https://plantuml.com/class-diagram

!theme gambio from ../gambio-puml-theme

package Gambio\Admin\Modules\ShippingModule\Services {

    class ShippingMethodFactory {
        + createShippingMethods(ShippingMethod ...$shippingMethods): ShippingMethods
        + createShippingMethodId(string $shippingMethodId): ShippingMethodId
    }


    interface CustomerDisallowedShippingMethodsReadService {
        + getCustomersDisallowedShippingMethods(int $customerId): ShippingMethods
    }

    interface CustomerDisallowedShippingMethodsWriteService {
        + setDisallowedShippingMethods(int $customerId, string ...$shippingMethodIds): void
    }

}

@enduml