@startuml
'https://plantuml.com/class-diagram

!theme gambio from ../gambio-puml-theme

package Gambio\Admin\Modules\Newsletter\Services {

    class CustomerFactory {
        + createCustomerIds(CustomerId ...$customerIds): CustomerIds
        + createCustomerId(int $customerId): CustomerId
    }


    interface CustomerNewsletterReadService {
        + getSubscribedCustomers(): CustomerIds
        + isCustomerSubscribed(int $customerId): bool
    }

    interface CustomerNewsletterWriteService {
        + subscribe(int $customerId): void
        + unsubscribe(int $customerId): void
    }

}

@enduml