@startuml
'https://plantuml.com/class-diagram

!theme gambio from ../gambio-puml-theme

package Gambio\Admin\Modules\Customer\Submodules\Memos\Model\Events {
	left to right direction

	class CustomerMemoCreated {
		- customerMemoId: CustomerMemoId
		+ {static} create(CustomerMemoId $customerMemoId): CustomerMemoCreated
		+ customerMemoId(): CustomerMemoId
	}

	class CustomerMemoDeleted{
		- customerMemoId: CustomerMemoId
		+ {static} create(CustomerMemoId $customerMemoId): CustomerMemoDeleted
		+ customerMemoId(): CustomerMemoId
	}

	class CustomerMemosContentUpdated{
		- customerMemoId: CustomerMemoId
		- content: string
		+ {static} create(CustomerMemoId $customerMemoId, string $content): CustomerMemoDeleted
		+ customerMemoId(): CustomerMemoId
		+ content(): string
	}
}

@enduml