name: "Product Options"
description: |
  The following endpoints can be used to manage the product options of this shop.

  Currently, the shop does no support all fields inside the documents completly. The following fields aren't
  supported yet: `stockType`